version: '3.4'

services:
  desafiotriagil:
    image: desafiotriagil
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - .:/tmp
    depends_on:
      - postgresql
    networks:
     - desafiotriagil-postgres-pgadmin4
    
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file: .env
      
    networks:
     - desafiotriagil-postgres-pgadmin4
    
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - desafiotriagil-postgres-pgadmin4

networks:
  desafiotriagil-postgres-pgadmin4:

  

  
  